---

  - hosts: all   # hangi sunucularda çalıştırılacak
    become: true # sudo olarak çalıştırsınmı
    tasks:

    - name: 1- apt update işlemini yapılması
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
         
    - name: 2- bu gorev apache yuklemesini gerceklestirir. 
      apt:
        name: apache2
      when: ansible_distribution == "Ubuntu"
    - name: 3- PHP yuklenmesi 
      apt:
        name: libapache2-mod-php
      when: ansible_distribution == "Ubuntu"